### ISSUE TITLE
I.waitFor* methods not working with v2.6 and playwright 0.12.1

### ISSUE THREAD

**Issue by akapitoha** [codecept-js/CodeceptJS#2314]
#### What are you trying to achieve?
In some tests I have methods like
```
I.waitForText(text, 25, locator)
I.waitForElement(locator, 10)
```
which where working fine.

#### What do you get instead?
After codecept and playwright updates methods fail without using timeout with error
`Evaluation failed: SyntaxError: The string did not match the expected pattern.`

### Details

* CodeceptJS version: 2.6
* NodeJS Version: 12.16.1
* Operating System: Mac os 10.14.6
* Playwright: 0.12.1

UPD: In this case I used custom locators.
in config file:
```
plugins: {
    customLocator: {
      enabled: true,
      attribute: "data-testid",
    },
  },
```
selector in page object: `emailField: "$login-input",`
then used in a test (as example): `I.waitForElement(login.emailField, 20)`

**Comment by PeterNgTr** [comment]
maybe wait for this fix https://github.com/Codeception/CodeceptJS/pull/2313

**Comment by akapitoha** [comment]
@PeterNgTr I see #2313 is fixed in 2.6.1, but I still get the same error for waitForElement().
with waitForText I get:
```
Evaluation failed: TypeError: $XPath is not a function. (In '$XPath(null, locator)', '$XPath' is "function $XPath(element, selector) {
```

**Comment by Georgegriff** [comment]
From slack i believe this may be around custom locators, that detail is missing from this ticket

**Comment by Georgegriff** [comment]
Related to: https://github.com/microsoft/playwright/issues/2197

Workaround: put css as strategy in custom locator plugin
```
plugins: {
    customLocator: {
      enabled: true,
      attribute: "data-testid",
      strategy: "css"
    },
  },
```

We can probably fix this whilst we wait for playwright if they plan to fix

**Comment by Georgegriff** [comment]
Playwright have confirmed they will keep their xpath heuristic as is, so won't be fixing this issue, but that is okay because the linked pr resolves the issue, I need to do some tidying up of the pr, test fixes

**Comment by mirao** [comment]
> @akapitoha 
> with waitForText I get:
> Evaluation failed: TypeError: $XPath is not a function. (In '$XPath(null, locator)', '$XPath' is "function $XPath(element, selector) ...

I got the same error when testing WebKit in Playwright: #2913

**Comment by VaasRamsay** [comment]
Looks like @Georgegriff's fix got reverted back
